// Emission: catalog + source texts -> texts/<lang>.lang + texts/languages.json,
// and the sync, offline `compileLocalization()` entry point the OpenRock build
// pipeline calls for `content.localization`.
"use strict";

const fs = require("fs");
const path = require("path");
const { parseLang, serializeLang } = require("./langFile.js");

const HEADER = "GENERATED by OpenRock localization - edit the source .lang / translation sheet, not this file.";

/** Fallback chain per key: that language's translation (any status) -> source text. */
function renderLangOutputs({ catalog, sourceTexts, langs }) {
    const out = new Map();
    const all = [catalog.sourceLang, ...langs.filter(l => l !== catalog.sourceLang)];
    for (const lang of all) {
        const entries = new Map();
        for (const [key, source] of sourceTexts) {
            entries.set(key, lang === catalog.sourceLang ? source : (catalog.entries[key]?.translations[lang]?.text ?? source));
        }
        out.set(`texts/${lang}.lang`, serializeLang(entries, { header: HEADER }));
    }
    out.set("texts/languages.json", JSON.stringify(all, null, 2) + "\n");
    return out;
}

/** Languages = config.languages ∪ any language with a translation in the catalog. */
function collectLangs(catalog, config) {
    const set = new Set(config.languages ?? []);
    for (const e of Object.values(catalog.entries)) for (const l of Object.keys(e.translations)) set.add(l);
    set.delete(catalog.sourceLang);
    return [...set].sort();
}

/**
 * `content.localization` directory layout:
 *   <dir>/<sourceLang>.lang      human-authored source text
 *   <dir>/catalog.json           translation state (optional; absent = source only)
 *   <dir>/localization.json      { sourceLang?, languages?, autoTranslate?, provider? } (optional)
 */
function compileLocalization(dir) {
    if (!fs.existsSync(dir)) return { bp: {}, rp: {} };
    const read = f => { const p = path.join(dir, f); return fs.existsSync(p) ? fs.readFileSync(p, "utf8") : null; };
    const config = JSON.parse(read("localization.json") ?? "{}");
    const catalogText = read("catalog.json");
    const catalog = catalogText ? JSON.parse(catalogText) : { version: 1, sourceLang: config.sourceLang ?? "en_US", entries: {} };
    const sourceLang = config.sourceLang ?? catalog.sourceLang;
    catalog.sourceLang = sourceLang;
    const sourceLangFile = read(`${sourceLang}.lang`);
    if (sourceLangFile === null) throw new Error(`localization: ${path.join(dir, sourceLang + ".lang")} (the source-language text) doesn't exist`);
    const sourceTexts = parseLang(sourceLangFile);

    const files = renderLangOutputs({ catalog, sourceTexts, langs: collectLangs(catalog, config) });
    const side = {};
    for (const [rel, text] of files) side[rel] = text;
    return { bp: { ...side }, rp: { ...side } };
}

module.exports = { renderLangOutputs, collectLangs, compileLocalization, HEADER };
