// Emission: catalog + source texts -> texts/<lang>.lang + texts/languages.json,
// and the sync, offline `compileLocalization()` entry point the OpenRock build
// pipeline calls for `content.localization`.
"use strict";

const fs = require("fs");
const path = require("path");
const { parseLang, serializeLang } = require("./langFile.js");

// Locales Minecraft itself ships; only these get a texts/<lang>.lang the client can pick by game language.
// Anything else (e.g. fil_PH) is reachable only through the per-player runtime table.
const GAME_LOCALES = new Set([
    "en_US", "en_GB", "de_DE", "es_ES", "es_MX", "fr_FR", "fr_CA", "it_IT", "ja_JP", "ko_KR", "pt_BR", "pt_PT",
    "ru_RU", "zh_CN", "zh_TW", "nl_NL", "bg_BG", "cs_CZ", "da_DK", "el_GR", "fi_FI", "hu_HU", "id_ID", "nb_NO",
    "pl_PL", "sk_SK", "sv_SE", "tr_TR", "uk_UA",
]);
// Opt-in (localization.json "aliasRegionalLocales": true): close regional variants reuse a sibling when the project has none.
const LOCALE_ALIASES = { en_GB: "en_US", es_MX: "es_ES", fr_CA: "fr_FR", pt_PT: "pt_BR", zh_TW: "zh_CN" };
const RUNTIME_MODULE_PREFIX = "export const LANGS = ";

const HEADER = "GENERATED by OpenRock localization - edit the source .lang / translation sheet, not this file.";

/** Fallback chain per key: that language's translation (any status) -> source text. */
function resolvedTables({ catalog, sourceTexts, langs, overrides = new Map() }) {
    const all = [catalog.sourceLang, ...langs.filter(l => l !== catalog.sourceLang)];
    const tables = new Map();
    for (const lang of all) {
        const entries = new Map();
        const own = overrides.get(lang);
        for (const [key, source] of sourceTexts) {
            entries.set(key, lang === catalog.sourceLang ? source : (own?.get(key) ?? catalog.entries[key]?.translations[lang]?.text ?? source));
        }
        if (own && lang !== catalog.sourceLang) for (const [key, text] of own) if (!entries.has(key)) entries.set(key, text);
        tables.set(lang, entries);
    }
    return tables;
}

/** texts/<lang>.lang + texts/languages.json for the real game locales (aliases fill gaps), source language first. */
function renderLangOutputs({ catalog, sourceTexts, langs, aliasRegionalLocales = false, overrides }) {
    const tables = resolvedTables({ catalog, sourceTexts, langs, overrides });
    const out = new Map();
    const game = new Map([...tables].filter(([lang]) => GAME_LOCALES.has(lang) || lang === catalog.sourceLang));
    if (aliasRegionalLocales) for (const [alias, base] of Object.entries(LOCALE_ALIASES)) if (!game.has(alias) && game.has(base)) game.set(alias, game.get(base));
    for (const [lang, entries] of game) out.set(`texts/${lang}.lang`, serializeLang(entries, { header: HEADER }));
    const ids = [...game.keys()].sort((a, b) => (a === catalog.sourceLang ? -1 : b === catalog.sourceLang ? 1 : a.localeCompare(b)));
    out.set("texts/languages.json", JSON.stringify(ids, null, 2) + "\n");
    return out;
}

/** JS source for the per-player runtime table: LANGS = { [id]: { name, table } } over ALL languages (incl. non-game locales). */
function renderRuntimeModule({ catalog, sourceTexts, langs, overrides }) {
    const langsOut = {};
    for (const [lang, entries] of resolvedTables({ catalog, sourceTexts, langs, overrides })) {
        const table = Object.fromEntries(entries);
        langsOut[lang] = { name: table["openchara.language.name"] ?? table["language.name"] ?? lang, table };
    }
    return `// GENERATED by OpenRock localization - do not edit.\n${RUNTIME_MODULE_PREFIX}${JSON.stringify(langsOut)};\n`;
}

/** Languages = config.languages ∪ any language with a translation in the catalog. */
function collectLangs(catalog, config) {
    const set = new Set(config.languages ?? []);
    for (const e of Object.values(catalog.entries)) for (const l of Object.keys(e.translations)) set.add(l);
    set.delete(catalog.sourceLang);
    return [...set].sort();
}

/**
 * `content.localization` directory layout:
 *   <dir>/<sourceLang>.lang      human-authored source text
 *   <dir>/catalog.json           translation state (optional; absent = source only)
 *   <dir>/localization.json      { sourceLang?, languages?, autoTranslate?, provider? } (optional)
 */
function compileLocalization(dir) {
    if (!fs.existsSync(dir)) return { bp: {}, rp: {} };
    const read = f => { const p = path.join(dir, f); return fs.existsSync(p) ? fs.readFileSync(p, "utf8") : null; };
    const config = JSON.parse(read("localization.json") ?? "{}");
    const catalogText = read("catalog.json");
    const catalog = catalogText ? JSON.parse(catalogText) : { version: 1, sourceLang: config.sourceLang ?? "en_US", entries: {} };
    const sourceLang = config.sourceLang ?? catalog.sourceLang;
    catalog.sourceLang = sourceLang;
    const sourceLangFile = read(`${sourceLang}.lang`);
    if (sourceLangFile === null) throw new Error(`localization: ${path.join(dir, sourceLang + ".lang")} (the source-language text) doesn't exist`);
    const sourceTexts = parseLang(sourceLangFile);

    // Hand-authored sibling <lang>.lang files are reviewed translations that win over the catalog (and add their own keys).
    const overrides = new Map();
    for (const f of fs.readdirSync(dir)) {
        const m = /^([A-Za-z]{2,3}(?:_[A-Za-z0-9]+)?).lang$/.exec(f);
        if (m && m[1] !== sourceLang) overrides.set(m[1], parseLang(fs.readFileSync(path.join(dir, f), "utf8")));
    }
    const langs = [...new Set([...collectLangs(catalog, config), ...overrides.keys()])].sort();
    const files = renderLangOutputs({ catalog, sourceTexts, langs, aliasRegionalLocales: Boolean(config.aliasRegionalLocales), overrides });
    const side = {};
    for (const [rel, text] of files) side[rel] = text;
    const runtime = renderRuntimeModule({ catalog, sourceTexts, langs, overrides });
    return { bp: { ...side, ".openrock-virtual/localization-tables.js": runtime }, rp: { ...side } };
}

module.exports = { renderLangOutputs, renderRuntimeModule, collectLangs, compileLocalization, HEADER, GAME_LOCALES, LOCALE_ALIASES, RUNTIME_MODULE_PREFIX };
